version: 2.1

jobs:
  check:
    docker:
      - image: circleci/circleci-cli:latest
    steps:
      - checkout
      - run:
          name: Pack orb and run lint
          command: |
            make lint

  lint:
    docker:
      - image: python:3.7.0-alpine3.8
    steps:
      - checkout
      - run:
          name: Install yamllint
          command: |
            pip3 install -U -v yamllint
      - run:
          name: Run yamllint
          command: |
            yamllint -s .

workflows:
  version: 2
  check-lint:
    jobs:
      - check:
          context: org-global
      - lint:
          context: org-global
