version: 2.1

jobs:
  validate:
    docker:
      - image: circleci/circleci-cli:latest
    steps:
      - checkout
      - run:
          name: Pack orb and run lint
          command: |
            make validate

  lint:
    docker:
      - image: python:3.7-stretch
    steps:
      - run:
          name: Install yamllint
          command: |
            pip3 install -U git+https://github.com/adrienverge/yamllint.git
      - checkout
      - run:
          name: Run yamllint
          command: |
            make yamllint

  publish:
    docker:
      - image: circleci/circleci-cli:latest
    steps:
      - checkout
      - run:
          name: Publish to production orb registry.
          command: |
            make publish

workflows:
  version: 2
  workflows:
    jobs:
      - validate:
          context: org-global
      - lint:
          context: org-global
      - publish:
          context: org-global
          filters:
            tags:
              only: /^.*/
            branches:
              ignore: /.*/
