version: 2.1

executors:
  circleci-cli:
    docker:
      - image: circleci/circleci-cli:alpine

jobs:
  validate:
    executor: circleci-cli
    steps:
      - run:
          name: Install make and bash
          command: |
            apk add --no-cache make bash
      - checkout
      - run:
          name: Pack orb and run lint
          command: |
            make validate

  lint:
    docker:
      - image: python:3.8-alpine
    steps:
      - run:
          name: Install make, bas and yamllint
          command: |
            apk add --no-cache make git bash
            pip3 install -U git+https://github.com/adrienverge/yamllint.git
      - checkout
      - run:
          name: Run yamllint
          command: |
            make yamllint

  publish:
    executor: circleci-cli
    steps:
      - run:
          name: Install make and bash
          command: |
            apk add --no-cache make bash
      - checkout
      - run:
          name: Publish to production orb registry.
          command: |
            make publish

workflows:
  version: 2
  workflows:
    jobs:
      - validate:
          context: org-global
      - lint:
          context: org-global
      - publish:
          context: org-global
          filters:
            tags:
              only: /^.*/
            branches:
              ignore: /.*/
